[build-system]
    requires = [
        "setuptools>=61.0",
        "wheel>=0.37.0",
        "pybind11>=2.6.0",
    ]
    build-backend = "setuptools.build_meta"

#[project]
#    name = "ak-memkit"
#    version = "0.0.1"
#    authors = [
#        {name = "AK", email = "akpainkiller32767@gmail.com"}
#    ]
#    description = "AK32767's mysterious memory reading toolkit"
#    readme = "README.md"
#    license = {text = "MIT"}
#    requires-python = ">=3.12"
#    classifiers = [
#        "Development Status :: 3 - Alpha",
#        "Intended Audience :: Developers",
#        "Topic :: Software Development :: Libraries :: Python Modules",
#        "Programming Language :: Python :: 3.12",
#        "Programming Language :: Python :: 3.13",
#        "Programming Language :: Python :: 3.14",
#        "Operating System :: Microsoft :: Windows",
#    ]
#
#    dependencies = [
#        "neac_controller @ git+https://github.com/AK-0x7FFF/NeacController.git",
#        "pyMeow @ git+https://github.com/AK-0x7FFF/pyMeow.git",
#        "memprocfs>=5.14.0",
#        "numpy",
#        "numba",
#        "scipy",
#        "deprecated",
#        "pybind11>=2.6.0",
#        "winappdbg @ git+https://github.com/MarioVilas/winappdbg.git",
#    ]
#
#[project.urls]
#    Homepage = "https://github.com/AK-0x7FFF/ak-memkit"
#    Repository = "https://github.com/AK-0x7FFF/ak-memkit"
#    "Issue Tracker" = "https://github.com/AK-0x7FFF/ak-memkit/issues"
#
#[tool.setuptools]
#    package-dir = {"" = "src"}
#    zip-safe = false
#
#[tool.setuptools.packages.find]
#    where = ["src"]
#
#[tool.setuptools.package-data]
#    "*" = ["*.pyd"]