from typing import TypedDict, Iterator, Generator, Any, Iterable


class NimPyException(Exception):
    ...


# Process
class _Process(TypedDict):
    name: str
    pid: int
    debug: bool
    handle: int
def enum_processes() -> Iterator[_Process]: ...
def open_process(process: str | int, debug: bool = False) -> _Process: ...
def process_exists(processName: str) -> bool: ...
def pid_exists(pid: int) -> bool: ...
def process_running(process: _Process) -> bool: ...
def get_process_id(processName: str) -> int: ...
def get_process_name(pid: int) -> str: ...
def get_process_path(process: _Process) -> str: ...
def close_process(process: _Process) -> None: ...


# Module
class _Module(TypedDict):
    name: str
    base: int
    end: int
    size: int
def enum_modules(process: _Process) -> Generator[_Module, None, None]: ...
def get_module(process: _Process, moduleName: str) -> _Module: ...
def module_exists(process: _Process, moduleName: str) -> bool: ...


# System
def system_name() -> str: ...
def is_64_bit(process: _Process) -> bool: ...
def get_os_error() -> int | str: ...


# Memory
def aob_scan_module(process: _Process, moduleName: str, pattern: str, relative: bool = False, single: bool = True, algorithm: int = 0) -> list[int]: ...
def aob_scan_range(process: _Process, pattern: str, rangeStart: int, rangeEnd: int, relative: bool = False, single: bool = True, algorithm: int = 0) -> list[int]: ...
def aob_scan_bytes(pattern: str, byteBuffer: bytes, single: bool = True, algorithm: int = 0) -> list[int]: ...
def r_ctype(process: _Process, address: int, ctype: Any) -> Any: ...
def r_floats(process: _Process, address: int, size: int) -> Iterable[float]: ...
def r_bytes(process: _Process, address: int, size: int): ...
def r_string(process: _Process, address: int, size: int = 30) -> str: ...
def allocate_memory(process: _Process, size: int, protection: int = 0) -> int: ...
def free_memory(process: _Process, address: int) -> bool: ...
